import { GenerationContext, GeneratorStage } from "./generator-stage-interface";
import { LayerArtifact } from "./layer-artifact";

/**
 * Class which represents a generator pipeline. This pipeline generates different layers, i.e. stages in order that is defined
 * within constructor.
 */
export class GeneratorPipeline {
    private readonly _pipelineStages: GeneratorStage[];
    private _pipelineOutputArtifact: LayerArtifact | undefined;

    constructor(...stages: GeneratorStage[]) {
        this._pipelineStages = stages;
    }

    /**
     * Method responsible for a sequential generation of all pipeline stages.
     *
     * @param context - Generation process context (may include previous results and other metadata).
     * @returns A promise that resolves to the final `LayerArtifact` generated by the pipeline.
     * @throws Will throw an error if there are no stages to be generated.
    */
    async generateStages(context: GenerationContext): Promise<LayerArtifact> {

        if (!this._pipelineStages || this._pipelineStages.length === 0) {
            throw new Error("No stages to be generated");
        }

        for (const stage of this._pipelineStages) {
            const layerArtifact = await stage.generateStage(context);

            let layerOutput = layerArtifact;
            if (stage.artifactSaver) {
                const savedArtifact = stage.artifactSaver.saveArtifact(layerArtifact);
                // if layerArtifact had been saved before, the output will use actual saved path
                layerOutput = savedArtifact;
            }

            this._pipelineOutputArtifact = layerOutput;
            context.previousResult = layerOutput;
        }

        return this._pipelineOutputArtifact!;
    }
}