import { EntityModel } from "@dataspecer/core-v2";
import { InMemorySemanticModel } from "@dataspecer/core-v2/semantic-model/in-memory";
import { LanguageString } from "@dataspecer/core-v2/semantic-model/concepts";

import { EntityModelRepresentative } from "./dialog-utilities";
import { getModelIri } from "../../util/iri-utils";
import { IRI } from "iri";

/**
 * Shared interface for entity dialogs.
 */
export interface EntityState {

  /**
   * Available models.
   */
  availableModels: EntityModelRepresentative<EntityModel>[];

  /**
   * Available writable models.
   * Those can be set as owners.
   */
  writableModels: EntityModelRepresentative<InMemorySemanticModel>[];

  /**
   * Entity owner.
   */
  model: EntityModelRepresentative<InMemorySemanticModel>;

  iri: string;

  name: LanguageString;

  description: LanguageString;

}

export interface EntityStateController {

  setModel: (model: EntityModelRepresentative<InMemorySemanticModel>) => void;

  setIri: (iri: string) => void;

  setName: (setter: (value: LanguageString) => LanguageString) => void;

  setDescription: (setter: (value: LanguageString) => LanguageString) => void;

}

export function createEntityController<State extends EntityState>(
  changeState: (next: State | ((prevState: State) => State)) => void,
): EntityStateController {

  const setModel = (model: EntityModelRepresentative<InMemorySemanticModel>) => {
    changeState((state) => {
      return {
        ...state,
        model: model,
        baseIri: getModelIri(model.model),
      };
    });
  };

  const setIri = (iri: string) => {
    changeState((state) => ({ ...state, iri }));
  };

  const setName = (setter: (value: LanguageString) => LanguageString): void => {
    changeState((state) => ({ ...state, name: setter(state.name) }));
  };

  const setDescription = (setter: (value: LanguageString) => LanguageString): void => {
    changeState((state) => ({ ...state, description: setter(state.description) }));
  };

  return {
    setModel,
    setIri,
    setName,
    setDescription,
  };
}

/**
 * Shared for interface for new entities.
 */
export interface CreateEntityState {

  iri: string;

  /**
   * IRI prefix.
   */
  iriPrefix: string;

  /**
   * If true, change in name result in generation of IRI.
   */
  isIriAutogenerated: boolean;

  /**
   * If true the IRI is relative with respect to model.
   */
  isIriRelative: boolean;

}

export function isRelativeIri(iri: string | undefined | null): boolean {
  if (iri === undefined || iri === null) {
    return true;
  }
  return (new IRI(iri).scheme()?.length ?? 0) === 0;
}

export interface CreateEntityStateController {

  setModel: (model: EntityModelRepresentative<InMemorySemanticModel>) => void;

  setIri: (iri: string) => void;

  setIsRelative: (value: boolean) => void;

  setName: (setter: (value: LanguageString) => LanguageString) => void;

}

export function createCreateEntityController<State extends (EntityState & CreateEntityState)>(
  changeState: (next: State | ((prevState: State) => State)) => void,
  controller: EntityStateController,
  /**
   * Function used to generate IRI from a name.
   */
  generateIriFromName: (name: string) => string,
): CreateEntityStateController {

  const setModel = (model: EntityModelRepresentative<InMemorySemanticModel>) => {
    controller.setModel(model);
    // Update IRI prefix.
    const iriPrefix = getModelIri(model.model);
    changeState(state => ({ ...state, iriPrefix }));
  };

  const setIri = (iri: string) => {
    controller.setIri(iri);
    // Turn off generation.
    changeState(state => ({ ...state, isIriAutogenerated: false }));
  };

  const setIsRelative = (value: boolean) => {
    // We also need to change value of the IRI.
    changeState((state) => ({ ...state, isIriRelative: value }));
    // TODO Implement
  };

  const setName = (setter: (value: LanguageString) => LanguageString): void => {
    // TODO Implement
    controller.setName(setter);
  };

  return {
    setModel,
    setIri,
    setIsRelative,
    setName,
  };
}


