import { VisualModel } from "@dataspecer/core-v2/visual-model";
import { ClassesContextType } from "../../context/classes-context";
import { ModelGraphContextType } from "../../context/model-context";
import { isRepresentingAttribute, prepareModels, representCardinalities, representClasses, representModel, representOwlThing, representRelationships, representUndefinedCardinality, sortRepresentatives } from "../utilities/dialog-utilities";
import { generateName } from "../../util/name-utils";
import { sanitizeDuplicitiesInRepresentativeLabels } from "../../utilities/label";
import { configuration } from "../../application";
import { getModelIri } from "../../util/iri-utils";
import { InMemorySemanticModel } from "@dataspecer/core-v2/semantic-model/in-memory";
import { EditAssociationDialogState } from "./edit-association-dialog-controller";

/**
 * Create and return state for new association.
 *
 * @param classesContext
 * @param graphContext
 * @param visualModel
 * @param language
 * @param semanticModel Default model to create association into.
 * @returns
 */
export function createCreateAssociationDialogState(
  classesContext: ClassesContextType,
  graphContext: ModelGraphContextType,
  visualModel: VisualModel | null,
  language: string,
  semanticModel: InMemorySemanticModel,
): EditAssociationDialogState {
  const models = prepareModels(graphContext, visualModel);
  const model = representModel(visualModel, semanticModel);

  const name = generateName();

  const availableClasses = sanitizeDuplicitiesInRepresentativeLabels(
    models.all, representClasses(models.raw, classesContext.classes));
  sortRepresentatives(language, availableClasses);

  const availableSpecializations = sanitizeDuplicitiesInRepresentativeLabels(
    models.all, representRelationships(models.raw, classesContext.relationships))
    .filter(item => !isRepresentingAttribute(item));
  sortRepresentatives(language, availableClasses);

  const owlThing = representOwlThing();

  return {
    language,
    availableModels: models.all,
    writableModels: models.writable,
    model: model,
    iri: configuration().nameToIri(name),
    iriPrefix: getModelIri(model.model),
    isIriAutogenerated: true,
    isIriRelative: true,
    name: { [language]: name },
    description: {},
    availableSpecializations,
    specializations:[],
    domain: owlThing,
    domainCardinality: representUndefinedCardinality(),
    availableDomainItems: [owlThing, ...availableClasses],
    range: owlThing,
    rangeCardinality: representUndefinedCardinality(),
    availableRangeItems: [owlThing, ...availableClasses],
    availableCardinalities: [representUndefinedCardinality(), ...representCardinalities()],
  };
}
