import { VisualModel } from "@dataspecer/core-v2/visual-model";
import { InMemorySemanticModel } from "@dataspecer/core-v2/semantic-model/in-memory";

import { ClassesContextType } from "../../context/classes-context";
import { ModelGraphContextType } from "../../context/model-context";
import { EditClassDialogState } from "./edit-class-dialog-controller";
import { representClasses, representModels, selectWritableModels, sortRepresentatives } from "../utilities/dialog-utilities";
import { generateName } from "../../util/name-utils";
import { sanitizeDuplicitiesInRepresentativeLabels } from "../../utilities/label";
import { configuration } from "../../application";
import { getModelIri } from "../../util/iri-utils";

export function createNewClassDialogState(
  classesContext: ClassesContextType,
  graphContext: ModelGraphContextType,
  visualModel: VisualModel | null,
  language: string,
  model: InMemorySemanticModel,
): EditClassDialogState {
  const models = [...graphContext.models.values()];
  const availableModels = representModels(visualModel, models);
  const writableModels = representModels(visualModel, selectWritableModels(models));

  const name = generateName();

  const availableClasses = sanitizeDuplicitiesInRepresentativeLabels(
    availableModels,
    representClasses(models, classesContext.classes));
  sortRepresentatives(language, availableClasses);

  return {
    language,
    availableModels,
    writableModels,
    model: representModels(visualModel, [model])[0],
    iri: configuration().nameToClassIri(name),
    iriPrefix: getModelIri(model),
    isIriAutogenerated: true,
    isIriRelative: false,
    name: { [language]: name },
    description: {},
    availableSpecializations: availableClasses,
    specializations: [],
  };
}
