import { Configuration, RelationshipIriGeneratorStrategy } from "./configuration";
import { lowerCamelCase, upperCamelCase } from "./policy/naming-style-policy";

/**
 * Generate relationship profile IRI.
 */
const relationshipProfileToIri: RelationshipIriGeneratorStrategy = (state) => {
  if (!state.isIriAutogenerated) {
    return state;
  }
  const domainName = upperCamelCase(
    state.domain.label[state.language] ?? "");
  const name = lowerCamelCase(
    state.name[state.language] ?? "");
  //
  return {
    ...state,
    iri: domainName + "." + name,
  };
};

export const defaultConfiguration: Configuration = Object.freeze({
  configurationName: "Default",
  languagePreferences: ["en", "cs"],
  classNameToIri: upperCamelCase,
  relationshipNameToIri: lowerCamelCase,
  relationshipProfileToIri,
  hideIdentifier: true,
  hideRelationCardinality: true,
  xSnapGrid: 10,
  ySnapGrid: 10,
  alignmentXSnapGrid: 20,
  alignmentYSnapGrid: 20,
  defaultModelColor: "#000069",
});
