import { useMemo } from "react";
import {
  BaseEntityProfileDialogController,
  createBaseEntityProfileDialogController,
} from "../base-entity-profile/base-entity-profile-dialog-controller";
import { DialogProps } from "../dialog-api";
import { EntityRepresentative, filterByModel, RelationshipRepresentative } from "../utilities/dialog-utilities";
import { AssociationProfileDialogState } from "./edit-association-profile-dialog-state";
import { configuration } from "../../application";
import { LanguageString } from "../../dataspecer/entity-model";
import { CmeSemanticModel } from "../../dataspecer/cme-model";
import {
  BaseRelationshipProfileDialogController,
  createBaseRelationshipProfileDialogController,
} from "../base-relationship-profile/base-relationship-profile-dialog-controller";
import { validateBaseEntityDialogState } from "../base-entity/base-entity-dialog-validation";

export interface EditAssociationProfileDialogController extends
  BaseEntityProfileDialogController<RelationshipRepresentative>,
  BaseRelationshipProfileDialogController<EntityRepresentative> { }

export function useEditAssociationProfileDialogController(
  { changeState }: DialogProps<AssociationProfileDialogState>,
): EditAssociationProfileDialogController {
  return useMemo(() => {

    const entityProfileController = createBaseEntityProfileDialogController(
      changeState, configuration().relationshipNameToIri);

    const relationshipProfileController = createBaseRelationshipProfileDialogController(
      changeState, filterByModel, filterByModel);

    const setModel = (model: CmeSemanticModel) => {
      entityProfileController.setModel(model);
      relationshipProfileController.updateDomains(model);
      relationshipProfileController.updateRanges(model);
      changeState(state => configuration().relationshipProfileToIri(state));
    };

    const setName = (setter: (value: LanguageString) => LanguageString): void => {
      changeState(state => {
        const result = { ...state, name: setter(state.name) };
        return configuration().relationshipProfileToIri(result);
      });
    };

    const setDomain = (value: EntityRepresentative): void => {
      relationshipProfileController.setDomain(value);
      changeState(state => configuration().relationshipProfileToIri(state));
    };

    const setIri = (iri: string) => {
      changeState((state) => validateBaseEntityDialogState({
        ...state, iri, isIriAutogenerated: false,
      }));
    };

    return {
      ...entityProfileController,
      ...relationshipProfileController,
      setModel,
      setName,
      setDomain,
      setIri,
    };
  }, [changeState]);
}
