PREFIX z: <https://slovník.gov.cz/základní/pojem/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
    ?outwardsRelation a z:typ-vztahu ;
        rdfs:domain %NODE% ;
        rdfs:range ?rangeElement ;
        skos:prefLabel ?outwardsRelationLabel ;
        skos:definition ?outwardsRelationDefinition ;
        skos:inScheme ?outwardsRelationGlossary .
    ?rangeElement a z:typ-objektu ;
        skos:prefLabel ?rangeLabel ;
        skos:definition ?rangeDefinition ;
        skos:inScheme ?rangeGlossary .
} WHERE {
    ?outwardsRelation a z:typ-vztahu ;
        skos:prefLabel ?outwardsRelationLabel ;
        skos:inScheme ?outwardsRelationGlossary ;
        rdfs:subClassOf [
            owl:allValuesFrom %NODE% ;
            owl:onProperty z:má-vztažený-prvek-1
        ] ;
        rdfs:subClassOf [
            owl:allValuesFrom ?rangeElement ;
            owl:onProperty z:má-vztažený-prvek-2
        ] .

    OPTIONAL { ?outwardsRelation skos:definition ?outwardsRelationDefinition }

    ?rangeElement skos:prefLabel ?rangeLabel ;
        skos:inScheme ?rangeGlossary .

    OPTIONAL { ?rangeElement skos:definition ?rangeDefinition }
}