PREFIX z: <https://slovník.gov.cz/základní/pojem/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT WHERE {
	?node a z:typ-objektu ;
		skos:prefLabel ?label ; skos:definition ?definition ;
		skos:inScheme ?glossary .

	FILTER (regex(lcase(str(?label)), %QUERY%, "i"))
}
LIMIT 20
