#!/bin/bash

# BACKEND - URL to the backend server
# BASE_PATH - Should not end with a slash (keep empty for root)

set -e # Exit with nonzero exit code if anything fails

# Paths configuration

MANAGER=""
MANAGER_BASE_PATH="$BASE_PATH$MANAGER"
MANAGER_URL="$MANAGER_BASE_PATH"

DATA_SPECIFICATION_EDITOR="/data-specification-editor"
DATA_SPECIFICATION_EDITOR_BASE_PATH="$BASE_PATH$DATA_SPECIFICATION_EDITOR"
DATA_SPECIFICATION_EDITOR_URL="$DATA_SPECIFICATION_EDITOR_BASE_PATH"

CONCEPTUAL_MODEL_EDITOR="/conceptual-model-editor"
CONCEPTUAL_MODEL_EDITOR_BASE_PATH="$BASE_PATH$CONCEPTUAL_MODEL_EDITOR"
CONCEPTUAL_MODEL_EDITOR_URL="$CONCEPTUAL_MODEL_EDITOR_BASE_PATH"

API_SPECIFICATION="/api-specification"
API_SPECIFICATION_BASE_PATH="$BASE_PATH$API_SPECIFICATION"
API_SPECIFICATION_URL="$API_SPECIFICATION_BASE_PATH"


printf "VITE_BACKEND=$BACKEND\nVITE_DEBUG_VERSION=$CF_PAGES_BRANCH@$(echo $CF_PAGES_COMMIT_SHA | head -c7) $(date -u +%F\ %H:%M:%S)\nVITE_MANAGER_URL=$MANAGER_URL\nVITE_WIKIDATA_ONTOLOGY_BACKEND=$WIKIDATA_ONTOLOGY_BACKEND\nVITE_BASE_PATH=$DATA_SPECIFICATION_EDITOR_BASE_PATH\n" > applications/data-specification-editor/.env.local

printf "VITE_PUBLIC_BASE_PATH=$CONCEPTUAL_MODEL_EDITOR_URL\nVITE_PUBLIC_APP_BACKEND=$BACKEND\nVITE_PUBLIC_APP_BACKEND_PACKAGE_ROOT=http://dataspecer.com/packages/local-root\nVITE_PUBLIC_MANAGER_PATH=$MANAGER_URL/\nVITE_PUBLIC_DSCME_LOGO_LINK=$MANAGER_URL/\n" > applications/conceptual-model-editor/.env.local
printf "VITE_PUBLIC_APP_AUTOSAVE_ENABLED_BY_DEFAULT=0\n" >> applications/conceptual-model-editor/.env.local

printf "VITE_DATA_SPECIFICATION_EDITOR=$DATA_SPECIFICATION_EDITOR_URL\nVITE_BACKEND=$BACKEND\nVITE_CME=$CONCEPTUAL_MODEL_EDITOR_URL\nVITE_API_SPECIFICATION_APPLICATION=$API_SPECIFICATION_URL\nVITE_BASE_PATH=$MANAGER_BASE_PATH\n" > applications/manager/.env.local
printf "VITE_GIT_COMMIT=$GIT_COMMIT\nVITE_GIT_REF=$GIT_REF\nVITE_GIT_COMMIT_DATE=$GIT_COMMIT_DATE\nVITE_GIT_COMMIT_NUMBER=$GIT_COMMIT_NUMBER\n" >> applications/manager/.env.local

printf "VITE_BACKEND=$BACKEND\n" > applications/api-specification/.env.local

if [ -n "$BASE_PATH" ]; then
  sed -i "2i\  \"homepage\": \"$BASE_PATH\"," applications/data-specification-editor/package.json
fi
