PREFIX z: <https://slovník.gov.cz/základní/pojem/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  %NODE% a z:typ-objektu ;
    skos:prefLabel ?label ;
    skos:definition ?definition;
    skos:inScheme ?glossary .
} WHERE {
  %NODE% a z:typ-objektu ;
    skos:prefLabel ?label .

  OPTIONAL { %NODE% skos:definition ?definition . }
  OPTIONAL { %NODE% skos:inScheme ?glossary . }
}
