PREFIX z: <https://slovník.gov.cz/základní/pojem/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


CONSTRUCT {
    <__search_results> <__has_search_result> ?node .
	?node
		<__order> ?len ;
		rdfs:subClassOf ?parent ;
		skos:prefLabel ?label ;
		skos:definition ?definition ;
		skos:inScheme ?glossary .
} WHERE {
	?node a z:typ-objektu ;
		skos:prefLabel ?label .
	OPTIONAL { ?node skos:definition ?definition . }
	OPTIONAL { ?node skos:inScheme ?glossary . }

	OPTIONAL {
		?node rdfs:subClassOf ?parent .
		FILTER NOT EXISTS {
			?parent skos:inScheme <https://slovník.gov.cz/základní/glosář> .
		}
	}

	{
		select ?node (MIN(strlen(str(?search_label)))  as ?len) WHERE {
			?node skos:prefLabel ?search_label .
			FILTER (regex(lcase(str(?search_label)), %QUERY%, "i"))
		}
		GROUP BY ?node
		ORDER BY ?len
		LIMIT 30
	}
}
