export * from "./web-specification";
export * from "./web-specification-conceptual";
export * from "./web-specification-conceptual-entity";
export * from "./web-specification-conceptual-property";
export * from "./web-specification-conceptual-type";
export * from "./web-specification-structure";
export * from "./web-specification-structure-entity";
export * from "./web-specification-structure-property";
export * from "./web-specification-structure-type";
